version: '3.3'
services:
  app:
    container_name: goapi
    hostname: goapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOST_FROM: dns
    ports:
      - 3000:3000
